# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 60ba838efaf9cd00a6a28befc45e132f4fda915c7746a14119dca44f4792e7f67d16f431031242264ccbce3c920bed9f94e0031980f8f4a07f92717dd957ae8f

test:
  secret_key_base: 61cfa4f886c4c14ca1de6d269514c86f55c3b3e9829ba4798c540bc1d2d1e7d28fa9d8a117f35577922a6c0d7c1be105241ba9cb3ea8cc822ce9b2af962d725e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
